CREATE TABLE codigo_Proce (
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `abreviatura` VARCHAR(10) DEFAULT NULL UNIQUE,
    `procedimiento` VARCHAR(200) DEFAULT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB CHARSET=utf8mb4;


-- Insertar procedimientos médicos y quirúrgicos con abreviaturas
INSERT INTO codigo_Proce (id, abreviatura, procedimiento) VALUES
(1, 'APP', 'Apéndicectomia'),
(2, 'AMP', 'Amputación'),
(3, 'ARTRO', 'Artrosentesis'),
(4, 'CBI', 'Cambio Bolsa Ileostomía'),
(5, 'CBU', 'Cambio Bolsa Urinaria'),
(6, 'CM', 'Cambio Membranas'),
(7, 'CSA', 'Cambio Sello Agua'),
(8, 'CSU', 'Cambios Sonda Ureteral'),
(9, 'CP', 'Cistostomía Percutánea'),
(10, 'CCS', 'Colación Cáteter Central Subclavio'),
(11, 'CCUA', 'Colación Cáteter Umbilical Arterial'),
(12, 'CCUV', 'Colación Cáteter Umbilical Venoso'),
(13, 'COL', 'Colecistectomía'),
(14, 'CCP', 'Colocación Canal Posterior'),
(15, 'CE', 'Colocación Enema'),
(16, 'CSF', 'Colocación Sonda Foley'),
(17, 'CSE', 'Colocación Surfactante'),
(18, 'CTE', 'Colocación Tubo Endotraqueal'),
(19, 'CTI', 'Colocación Tubo Intercostal'),
(20, 'CTV', 'Colocación Tubo Ventilación'),
(21, 'CV', 'Colocación Vendajes'),
(22, 'CVC', 'Colocación Vía Central'),
(23, 'CY', 'Colocación Yesos'),
(25, 'CURA', 'Curación Heridas'),
(26, 'DIPE', 'Diálisis Peritoneal'),
(27, 'DOP', 'Doppler'),
(28, 'DA', 'Drenaje Absceso'),
(29, 'DC', 'Drenaje Colecciones'),
(30, 'DHCEL', 'Drenaje Hidrocele'),
(31, 'DP', 'Drenaje Penitomal'),
(32, 'ECG', 'Electrocardiograma'),
(33, 'EN', 'Empaque Nasal'),
(34, 'ELIPO', 'Escisión Lipoma'),
(35, 'ESP', 'Espirometría'),
(37, 'ET', 'Exanguinotransfusión'),
(38, 'EA', 'Exploración Abdominal'),
(39, 'EM', 'Exploración Mama'),
(40, 'ECE', 'Extracción Cuerpo Extraño'),
(41, 'EXLIPO', 'Extracción Lipomas'),
(42, 'EU', 'Extracción Uña'),
(43, 'EXNAS', 'Extracción Nasal'),
(44, 'FAST', 'FAST'),
(45, 'FT', 'Fototerapia'),
(46, 'GASO', 'Gasometría'),
(47, 'GLUC', 'Glucometrías'),
(48, 'HEMO', 'Hemocultivos'),
(49, 'HEM', 'Hemorroidectomía'),
(50, 'HE', 'Herniorrafias'),
(51, 'HEP', 'Hernioplastias'),
(52, 'HC', 'Hidrocectomía Compleja'),
(53, 'HI', 'Hisopados'),
(54, 'INF', 'Infiltraciones'),
(55, 'IO', 'Intraoseo'),
(56, 'ISU', 'Irrigación Sonda Uritaria'),
(57, 'LE', 'Laparotomías Exploratorias'),
(58, 'LO', 'Lavado Oído'),
(59, 'LQ', 'Lavado Quemado'),
(60, 'LYD', 'Lavados y Debridamientos'),
(61, 'MPC', 'Manejo Paciente Crítico'),
(62, 'RCP', 'Maniobras RCP'),
(63, 'MC', 'Manipulación Cerrada'),
(64, 'MCC', 'Manipulación Cerrada Cadera'),
(65, 'MCCO', 'Manipulación Cerrada Codo'),
(66, 'MCH', 'Manipulación Cerrada Hombro'),
(67, 'MICTO', 'Miomectomía'),
(68, 'ONI', 'Onicectomía'),
(69, 'OQP', 'Orquidopexia'),
(70, 'OS', 'Osteosíntesis'),
(71, 'OTRO', 'Otro'),
(72, 'PAR', 'Paracentesis'),
(73, 'PST', 'Postectomía'),
(74, 'PL', 'Punción Lumbar'),
(75, 'RAD', 'Radiografías'),
(76, 'RCF', 'Recolocar Fijador'),
(77, 'RL', 'Resección Lipoma'),
(78, 'RQS', 'Resección Quiste Sebáceo'),
(79, 'RQ', 'Resección Quistes'),
(80, 'RC', 'Retiro Canales'),
(81, 'RCL', 'Retiro Clavo'),
(82, 'RCO', 'Retiro Colecistostomía'),
(83, 'RDJ', 'Retiro Drenaje J/P'),
(84, 'RGQ', 'Retiro Grapas Quirúrgicas'),
(85, 'RMA', 'Retiro Material'),
(86, 'RPEN', 'Retiro Penrose'),
(87, 'RPRON', 'Retiro Perone'),
(88, 'RPT', 'Retiro Puntos'),
(89, 'RS', 'Retiro Sonda'),
(90, 'RTI', 'Retiro Tubo Intercostal'),
(91, 'RVA', 'Retiro VAC'),
(92, 'RY', 'Retiro Yesos'),
(93, 'RDJP', 'Retiro Drenaje Jackson-Pratt'),
(94, 'SFE', 'Solución Fijación Externo'),
(95, 'SOG', 'Sonda Orogástrica'),
(96, 'SCC', 'Sutura Compleja Cara'),
(97, 'ST', 'Suturas'),
(98, 'TEN', 'Tenorrafias (Una o Más)'),
(99, 'TA', 'Testículo Agudo'),
(100, 'TBC', 'Toma Biopsias'),
(101, 'TOM', 'Tomografías'),
(102, 'TORA', 'Toracentesis'),
(103, 'US', 'Ultrasonidos'),
(104, 'VENO', 'Venodisección'),
(105, 'DRL', 'Drenaje Linfático'),
(106, 'PR', 'Prolapso Rectal'),
(107, 'DH', 'Drenaje Hematoma'),
(108, 'CFE', 'Colocación Fijador Externo'),
(109, 'PO', 'Preoperatorio'),
(110, 'CEN', 'Centellograma'),
(111, 'TBCU', 'Toma Cultivo'),
(112, 'ERNM', 'Estudio RNM'),
(113, 'ETAC', 'Estudio TAC'),
(114, 'EUSG', 'Estudio USG'),
(115, 'AMEU', 'AMEU'),
(116, 'CES', 'Cesárea'),
(117, 'OT', 'Obliteración Tubárica'),
(118, 'PES', 'Parto Eutócico Simple'),
(119, 'UEV', 'Ultrasonido Endovaginal'),
(120, 'UG', 'Ultrasonido Ginecológico'),
(121, 'TBCB', 'Toma Biopsia'),
(122, 'MIO', 'Miorrafia');
